# Generated by Django 3.1.1 on 2021-04-24 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20210424_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('type', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('describe', models.TextField(default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.item')),
            ],
        ),
    ]
