# Generated by Django 3.1.1 on 2021-05-06 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_scenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='')),
                ('path', models.TextField(default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.item')),
            ],
        ),
    ]
