# Generated by Django 3.1.1 on 2021-06-07 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.TextField(default='')),
                ('date', models.TextField(default='')),
                ('version', models.TextField(default='')),
                ('bus_type', models.TextField(default='')),
                ('communication_method', models.TextField(default='')),
                ('refresh_cycle', models.TextField(default='')),
                ('frame_header', models.TextField(default='')),
                ('frame_tail', models.TextField(default='')),
                ('message_length', models.TextField(default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.item')),
            ],
        ),
    ]
