# Generated by Django 3.1.1 on 2021-06-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_scripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripts',
            name='check_method',
            field=models.TextField(default=''),
        ),
    ]
