# Generated by Django 3.1.1 on 2021-06-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_scripts_check_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scripts',
            new_name='Protocol',
        ),
    ]
