# Generated by Django 3.1.1 on 2021-06-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_auto_20210607_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocol',
            old_name='message_length',
            new_name='configuration',
        ),
    ]
