# Generated by Django 3.1.1 on 2021-06-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0012_variable_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='value',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='')),
                ('function', models.TextField(default='')),
                ('data', models.TextField(default='')),
                ('TF', models.TextField(default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.item')),
                ('paths', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.paths')),
            ],
        ),
    ]
