# Generated by Django 3.1.1 on 2021-06-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0013_auto_20210619_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdata',
            name='item',
        ),
    ]
