# Generated by Django 3.1.1 on 2021-06-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0015_remove_protocol_refresh_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='length',
            field=models.TextField(default=''),
        ),
    ]
