# Generated by Django 3.1.1 on 2021-04-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0002_auto_20210424_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.item')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.personnel')),
            ],
        ),
    ]
