# Generated by Django 3.1.1 on 2021-06-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0002_edge_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='label',
            field=models.TextField(default='', unique=True),
        ),
    ]
